[build]
builder = "NIXPACKS"
buildCommand = "curl -LsSf https://astral.sh/uv/install.sh | sh -s -- -y && ~/.local/bin/uv --version && ~/.local/bin/uv sync --frozen --no-dev"

[deploy]
startCommand = "./.venv/bin/uvicorn backend.main:app --host 0.0.0.0 --port ${PORT}"
healthcheckPath = "/health"
healthcheckTimeout = 100


